### ISSUE TITLE
json view of dataset encoded as string?

### ISSUE THREAD

**Issue by dblodgett-usgs** [xpublish-community/xpublish-opendap#57]
Requests like: 

`https://labs-beta.waterdata.usgs.gov/api/xpublish/UofIMETDATA/json` 

comes through wrapped in ' ' so it gets interpreted as a string instead of json. 

Can we get that to come out as json?

**Comment by abkfenris** [comment]
Hi @dblodgett-usgs, it looks like that an issue with a [Catalog-to-Xpublish](https://github.com/xpublish-experiments/Catalog-To-Xpublish/) specific route rather than an OpenDAP plugin route:

https://github.com/xpublish-experiments/Catalog-To-Xpublish/blob/9731e0f3338c625d7a47ab96979e04e92c29b747/src/catalog_to_xpublish/routers/stac_router.py#L66-L73

https://github.com/xpublish-experiments/Catalog-To-Xpublish/blob/9731e0f3338c625d7a47ab96979e04e92c29b747/src/catalog_to_xpublish/routers/stac_router.py#L94C1-L98C10

I think the `json.dumps` may be unnecessary, and causing a string to be passed into the `JSONResponse` rather than something it can parse. I think the `self.catalog_endpoint_obj.catalog_obj.to_dict()` can be passed into `JSONResponse` directly.

**Comment by aufdenkampe** [comment]
@abkfenris, thanks for taking the time to dive into this issue a bit and identify the code that is causing the errors! 
@sjordan29, is this something you might be able to fix and test?

**Comment by sjordan29** [comment]
Yes, thank you @abkfenris! @aufdenkampe, can do.

**Comment by sjordan29** [comment]
Thanks again for digging into this @abkfenris. Made the fix on the Catalog-To-Xpublish side via [PR 12](https://github.com/xpublish-experiments/Catalog-To-Xpublish/pull/12).
